version: "3"
services:

  frontend:
    container_name: personal-nextjs
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend/app
    ports:
      - 3000:3000
    networks:
      - personal

networks:
  personal:
    driver: bridge

volumes:
  mysql-data:
